### ISSUE TITLE
Container MariaDB unhealthy

### ISSUE THREAD

**Issue by rafael-hsm** [LerianStudio/midaz-stack#10]
![Image](https://github.com/user-attachments/assets/01ca1f94-8b7c-4455-b205-8dcfa90a17f5)

MariaDB Container Unhealthy
When running the following commands:

docker logs --tail=50 midaz-audit-db
docker inspect midaz-audit-db | jq '.[] | .State.Health'
to check the last log messages, the Docker logs show the following error:

`OCI runtime exec failed: exec failed: unable to start container process: exec: "mysqladmin": executable file not found in $PATH: unknown`
I tried setting MariaDB to use mariadb instead of mysqladmin for the health check, but after this change, MariaDB started running, while midaz-console stopped working.

Here is the modification I made to the docker-compose file:

```
healthcheck:
  test: ["CMD", "mariadb", "-u", "root", "-p${TRILLIAN_DATABASE_ROOT_PASSWORD}", "-e", "SELECT 1"]
  interval: 10s
  timeout: 5s
  retries: 5
```

I execute the project in WSL2 with Ubutnu 24.04
